In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [3]:
type(a)

numpy.ndarray

In [4]:

a_mul = np.array([[1,2,3,1],
                  [4,5,6,7],
                  [6,8,9,3],
                  [5,6,8,8]])

print(a_mul.shape)

(4, 4)


In [5]:
print(a_mul.ndim)


2


In [6]:
print(a_mul.size)


16


In [7]:
a_mull = np.array([[[1,2,3,1],
                    [4,5,6,7],
                    [5,6,8,8]],
                 [[1,1,1,1],
                  [1,1,1,1],
                  [1,1,1,1]]])

print(a_mull)

[[[1 2 3 1]
  [4 5 6 7]
  [5 6 8 8]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [8]:
print(a_mull.shape)

(2, 3, 4)


In [9]:
print(a_mull.ndim)


3


In [10]:
a = np.full((2,3,4), 9)

print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]


In [11]:
x_values = np.arange(0, 1000, 5)




In [12]:
x_values = np.arange(0, 1000, 5)  #  generating an array x_values with values starting from 0, incrementing by 5, and stopping before 1000.
 
print(x_values) 

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


In [13]:
x_values = np.linspace(0, 1000, 100)

print(x_values) #generating an array x_values with 100 values that are evenly spaced between 0 and 1000 (inclusive).


[   0.           10.1010101    20.2020202    30.3030303    40.4040404
   50.50505051   60.60606061   70.70707071   80.80808081   90.90909091
  101.01010101  111.11111111  121.21212121  131.31313131  141.41414141
  151.51515152  161.61616162  171.71717172  181.81818182  191.91919192
  202.02020202  212.12121212  222.22222222  232.32323232  242.42424242
  252.52525253  262.62626263  272.72727273  282.82828283  292.92929293
  303.03030303  313.13131313  323.23232323  333.33333333  343.43434343
  353.53535354  363.63636364  373.73737374  383.83838384  393.93939394
  404.04040404  414.14141414  424.24242424  434.34343434  444.44444444
  454.54545455  464.64646465  474.74747475  484.84848485  494.94949495
  505.05050505  515.15151515  525.25252525  535.35353535  545.45454545
  555.55555556  565.65656566  575.75757576  585.85858586  595.95959596
  606.06060606  616.16161616  626.26262626  636.36363636  646.46464646
  656.56565657  666.66666667  676.76767677  686.86868687  696.96969697
  707.0

In [14]:
l1 = [1,2,3]



a1 = np.array(l1)
a2 = np.array([[1],
              [2]])



print(a1 + a2)



[[2 3 4]
 [3 4 5]]


In [24]:
a = np.array([[1,2,3],
              [4,5,6]])

print(np.delete(a, 1, 0)) # get rid of second row, delete a row with index 1

print(a.size)



[[1 2 3]]
6
