In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [5]:
type(a)

numpy.ndarray

In [6]:

a_mul = np.array([[1,2,3,1],
                  [4,5,6,7],
                  [6,8,9,3],
                  [5,6,8,8]])

print(a_mul.shape)

(4, 4)


In [7]:
print(a_mul.ndim)


2


In [8]:
print(a_mul.size)


16


In [15]:
a_mull = np.array([[[1,2,3,1],
                    [4,5,6,7],
                    [5,6,8,8]],
                 [[1,1,1,1],
                  [1,1,1,1],
                  [1,1,1,1]]])

print(a_mull)

[[[1 2 3 1]
  [4 5 6 7]
  [5 6 8 8]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


In [13]:
print(a_mull.shape)

(2, 3, 4)


In [14]:
print(a_mull.ndim)


3


In [16]:
a = np.full((2,3,4), 9)

print(a)

[[[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]

 [[9 9 9 9]
  [9 9 9 9]
  [9 9 9 9]]]
